// Shared task group color definitions
export const GROUP_COLORS = [
  {
    id: 'blue',
    name: 'Blue',
    headerBg: 'bg-blue-100',
    headerText: 'text-blue-800',
    headerBorder: 'border-l-blue-500',
    badgeBg: 'bg-blue-100 text-blue-700',
    dotColor: 'bg-blue-500',
    lightBg: 'bg-blue-50/30',
  },
  {
    id: 'green',
    name: 'Green',
    headerBg: 'bg-green-100',
    headerText: 'text-green-800',
    headerBorder: 'border-l-green-500',
    badgeBg: 'bg-green-100 text-green-700',
    dotColor: 'bg-green-500',
    lightBg: 'bg-green-50/30',
  },
  {
    id: 'orange',
    name: 'Orange',
    headerBg: 'bg-orange-100',
    headerText: 'text-orange-800',
    headerBorder: 'border-l-orange-500',
    badgeBg: 'bg-orange-100 text-orange-700',
    dotColor: 'bg-orange-500',
    lightBg: 'bg-orange-50/30',
  },
  {
    id: 'purple',
    name: 'Purple',
    headerBg: 'bg-purple-100',
    headerText: 'text-purple-800',
    headerBorder: 'border-l-purple-500',
    badgeBg: 'bg-purple-100 text-purple-700',
    dotColor: 'bg-purple-500',
    lightBg: 'bg-purple-50/30',
  },
  {
    id: 'rose',
    name: 'Rose',
    headerBg: 'bg-rose-100',
    headerText: 'text-rose-800',
    headerBorder: 'border-l-rose-500',
    badgeBg: 'bg-rose-100 text-rose-700',
    dotColor: 'bg-rose-500',
    lightBg: 'bg-rose-50/30',
  },
  {
    id: 'teal',
    name: 'Teal',
    headerBg: 'bg-teal-100',
    headerText: 'text-teal-800',
    headerBorder: 'border-l-teal-500',
    badgeBg: 'bg-teal-100 text-teal-700',
    dotColor: 'bg-teal-500',
    lightBg: 'bg-teal-50/30',
  },
  {
    id: 'amber',
    name: 'Amber',
    headerBg: 'bg-amber-100',
    headerText: 'text-amber-800',
    headerBorder: 'border-l-amber-500',
    badgeBg: 'bg-amber-100 text-amber-700',
    dotColor: 'bg-amber-500',
    lightBg: 'bg-amber-50/30',
  },
  {
    id: 'indigo',
    name: 'Indigo',
    headerBg: 'bg-indigo-100',
    headerText: 'text-indigo-800',
    headerBorder: 'border-l-indigo-500',
    badgeBg: 'bg-indigo-100 text-indigo-700',
    dotColor: 'bg-indigo-500',
    lightBg: 'bg-indigo-50/30',
  },
  {
    id: 'pink',
    name: 'Pink',
    headerBg: 'bg-pink-100',
    headerText: 'text-pink-800',
    headerBorder: 'border-l-pink-500',
    badgeBg: 'bg-pink-100 text-pink-700',
    dotColor: 'bg-pink-500',
    lightBg: 'bg-pink-50/30',
  },
  {
    id: 'slate',
    name: 'Slate',
    headerBg: 'bg-slate-100',
    headerText: 'text-slate-800',
    headerBorder: 'border-l-slate-500',
    badgeBg: 'bg-slate-100 text-slate-700',
    dotColor: 'bg-slate-500',
    lightBg: 'bg-slate-50/30',
  },
];
